//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackableEntities.EF.Tests.Edmx
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;
    using TrackableEntities;
    using TrackableEntities.Client;
    
    [JsonObject(IsReference = true)]
    [DataContract(IsReference = true, Namespace = "http://schemas.datacontract.org/2004/07/TrackableEntities.Models")]
    public partial class CultureCodes : ModelBase<CultureCodes>, IEquatable<CultureCodes>, ITrackable
    {
        
    	[DataMember]
    	public int culture_codes_id
    	{ 
    		get { return _culture_codes_id; }
    		set
    		{
    			if (Equals(value, _culture_codes_id)) return;
    			_culture_codes_id = value;
    			NotifyPropertyChanged(m => m.culture_codes_id);
    		}
    	}
    	private int _culture_codes_id;
        
    	[DataMember]
    	public string culture_codes_name
    	{ 
    		get { return _culture_codes_name; }
    		set
    		{
    			if (Equals(value, _culture_codes_name)) return;
    			_culture_codes_name = value;
    			NotifyPropertyChanged(m => m.culture_codes_name);
    		}
    	}
    	private string _culture_codes_name;
    
        #region Change Tracking
    
    	[DataMember]
    	public TrackingState TrackingState { get; set; }
    
    	[DataMember]
    	public ICollection<string> ModifiedProperties { get; set; }
    
    	[JsonProperty, DataMember]
    	private Guid EntityIdentifier { get; set; }
    
    	#pragma warning disable 414
    
    	[JsonProperty, DataMember]
    	private Guid _entityIdentity = default(Guid);
    
    	#pragma warning restore 414
    
    	bool IEquatable<CultureCodes>.Equals(CultureCodes other)
    	{
    		if (EntityIdentifier != default(Guid))
    			return EntityIdentifier == other.EntityIdentifier;
    		return false;
    	}
    
        #endregion
    }
}
