//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackableEntities.EF.Tests.Edmx
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductsModelContext : DbContext
    {
        static ProductsModelContext()
        {
            Database.SetInitializer(new NullDatabaseInitializer<ProductsModelContext>());
        }
    
        public ProductsModelContext()
            : base("name=ProductsModelContext")
        {
    		Configuration.ProxyCreationEnabled = false;
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CultureCodes> CultureCodes { get; set; }
        public virtual DbSet<Localization> Localization { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ResourceKey> ResourceKeys { get; set; }
    }
}
